/**
 * Generate src/lib/theme.ts from @maizzle/tailwindcss.
 *
 * react-email's <Tailwind theme="..."> prop imports the string inside
 * `@layer theme`, where `@custom-variant` / `@utility` are illegal, so
 * only the `@theme {}` blocks survive. Variants and mso-* utilities are
 * registered through the plugin API in src/lib/tailwind.ts instead.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '../node_modules/@maizzle/tailwindcss')
const files = ['reset.css', 'theme/colors.css', 'theme/text.css', 'theme/shadows.css', 'theme/filters.css', 'theme/spacing.css', 'theme/borders.css']

let css = files
  .map(f => readFileSync(join(root, f), 'utf8'))
  .join('\n')
  .split('\n')
  .filter(line => !/^\s*@custom-variant\b/.test(line))
  .join('\n')

// Breakpoints come from the plugin (addVariant) so their emit order stays
// desktop-first; theme breakpoint tokens would re-sort them ascending.
css += '\n@theme { --breakpoint-*: initial; --radius-full: 9999px; }\n'

const out = `// Generated by scripts/build-theme.ts from @maizzle/tailwindcss — do not edit.
export const theme = ${JSON.stringify(css)}
`
writeFileSync(new URL('../src/lib/theme.ts', import.meta.url), out)
console.log(`theme.ts written (${css.length} chars)`)
